title: <p align="center"> Nikhil Singh </p>

logo: "/images/zupeee.jpg?raw=true"

description:
  <p align="center">
  <a href="https://github.com/nikhilbyte">Github</a> |
  <a href="https://zindi.africa/users/niksss">Zindi</a> |
  <a href="https://huggingface.co/niksss">Huggingface</a> |
  <a href="https://www.drivendata.org/users/niksss/">DrivenData</a> |
  <a href="https://www.topcoder.com/members/nikhilsinghh">Topcoder</a>
  </p>
  
  <p align="justify">
  Scientist and NLP enthusiast specializing in multi-modal information retrieval and Transformer-based models. With expertise in frameworks like PyTorch, TensorFlow, and Huggingface, I build scalable systems for text, image, video, and audio understanding. A published researcher with hands-on experience in cutting-edge AI and a passion for solving complex challenges through innovation.
  <br><br>
  Along with researching, I participate in tons of Data Science Competitions and would love to talk about the tricks to better the performance on the leaderboard.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
